function [scenario, egoVehicle] = Scenario_Torino_Pinerolo_2()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 01-Apr-2022 22:50:23

% Construct a drivingScenario object.
scenario = drivingScenario('GeographicReference', [44.9031 7.4381 0], ...
    'VerticalAxis', 'Y');

% Add all road segments
roadCenters = [-2533.525 -660.5997 0.007832312;
    -1765.003 -366.3078 0.2151032;
    -1487.665 -257.8598 0.2215735;
    -1420.546 -225.4474 0.1741911;
    -1369.564 -193.1975 0.1280504;
    -1321.251 -157.3015 0.08643477;
    -1278.483 -119.0149 0.04874494;
    -1231.913 -67.41526 0.01698307;
    -1198.67 -22.65845 -0.01248784;
    -1144.79 67.00241 -0.03347376;
    -1096.623 143.3402 -0.05128544;
    -1024.314 222.864 -0.06101424;
    -957.6812 277.374 -0.06670862;
    -875.3887 330.6713 -0.06578111;
    -787.3409 377.9345 -0.05973131;
    -720.516 413.777 -0.0540738;
    -480.305 542.765 -0.041188;
    -442.942 562.822 0.0202643;
    146.092 878.373 0.179719;
    307.54 966.494 0.46369;
    360.7306 999.0465 0.6546059;
    408.867 1031.444 0.8071521;
    449.4539 1062.274 0.9218568;
    490.5217 1097.65 0.9972245;
    537.4712 1142.65 1.031808;
    584.3879 1193.374 1.026551;
    659.4349 1282.252 0.9720232;
    812.2384 1464.212 0.8471251;
    897.188 1557.973 0.7073422;
    980.5698 1663.77 0.5240451];
laneSpecification = lanespec(3, 'Width', 3.5);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Autostrada del Pinerolese');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-2498.03 -650.5503 0.03], ...
    'Yaw', 21, ...
    'Roll', 0.000317789380798706, ...
    'FrontOverhang', 0.9, ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');

