function [scenario, egoVehicle] = Copy_of_ScenarioTest6_curva_sxLK()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 12-Jan-2022 18:56:01

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-400.0000         0         0
 -300.0000         0         0
 -200.0000         0         0
 -100.0000         0         0
         0         0         0
    4.0000    0.0001         0
   58.5538    0.3012         0
  113.0728    2.1703         0
  167.3975    7.0625         0
  221.1259   16.4031         0
  222.2208   16.6676         0
  319.4434   49.6358         0
  416.6660  108.3930         0
  513.8885  207.9054         0
  611.1111  504.1659         0
  611.1256 -260.7920         0
  608.2932 -202.7807         0
  600.9911 -139.5736         0
  590.6983  -73.0997         0
  578.8689   -5.0141         0
  577.9802         0         0
  555.7582  125.3563         0
  533.5363  250.7125         0
  511.3144  376.0688         0];

laneSpecification = lanespec(3, 'Width', 3.5);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-400 0 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [0 -300 0;
    0 -200 0];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

