function [scenario, egoVehicle] = ScenarioTest6_curva_sxLK()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.9 (R2020b) and Automated Driving Toolbox 3.2 (R2020b).
% Generated on: 12-Jan-2022 18:56:01

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-100 800 0;
    -47 388 0;
    43 55 0;
    169 -110 0;
    409 -237 0;
    723 -271 0;
    994 -279 0];
laneSpecification = lanespec(3, 'Width', 3.5);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-103.067732343214 796.690714841122 0.01], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-103.067732343214 796.690714841122 0.01;
    -102 787.78 0.01];
speed = [30;30];
trajectory(egoVehicle, waypoints, speed);

